# Generated by Django 5.2.11 on 2026-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
