# Generated by Django 5.2.11 on 2026-02-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_vendor_profile_vendor_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_request',
            name='vendor',
        ),
    ]
