# Generated by Django 5.2.11 on 2026-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='code_offer',
            field=models.CharField(max_length=10),
        ),
    ]
